[workspace]
authors = [
    "Arijit Dasgupta <arijitdg@mit.edu>",
    "Matin Ghavami <mghavami@mit.edu>",
    "Xiaoyan Wang <xyw@mit.edu>"
]
channels = ["conda-forge"]
name = "python"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
