\newcommand{\L}{\mathcal{L}}
\newcommand{\N}{\mathbb{N}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\SE}{\mathrm{SE}}
\newcommand{\argmax}{\operatorname*{argmax}}

# Mathematical Description of Fuzzy Metaball Rendering

## Notation

$\N_n$ denotes the set $\{1, 2, \ldots, n\}$. $\SE(d)$ denotes the group of
$d$-dimensional rigid transformations (hence $\SE(3)$ is the group of poses).
$S^d$ denotes the $d$-dimensional sphere, i.e. the set of $d + 1$ dimensional
unit vectors.

The notation $\mathrm{symbol} := \mathrm{expression}$ offers the definition of "symbol" in terms of the "expression."

Greek letters are unknowns, Latin letters are known

Writing $(\tau, \rho) := \pi $ for $\pi \in \SE(3)$ means that $\pi$'s translational
component is $\tau$ and it's rotational component is $\rho$. For $v \in \R^d$
we write $\pi\cdot v$ to denote $v$ transformed by $\pi$.

| Symbol | Type | Meaning |
|:------:|:----:|:--------|
| $N$    | $\N$ | number of fuzzy metaballs |
| $T$    | $\N$ | number of time steps (frames) |
| $H$    | $\N$ | height of each observed frame in pixels |
| $W$    | $\N$ | width of each observed frame in pixels |
| $i$    | $\N_H$ | index ranging over the rows in each observed frame |
| $j$    | $\N_W$ | index ranging over the columns in each observed frame |
| $k$    | $\N_N$ | index ranging over the fuzzy metaballs |
| $t$    | $\N_T$ | index ranging over frames |
| $v_{ij}$ | $S^2$ | direction of the ray corresponding to pixel $(i, j)$ in the camera frame |
| $\pi^{(t)}$ | $\SE(3)$ | camera pose in world frame at frame $t$ |
| $\mu_k$ | $\R^3$ | the mean vector of the $k$-the fuzzy metaball |
| $\Pi_k$ | $\R^{3\times 3}_{\succ 0}$ | the precision matrix (inverse covariance) of the $k$-the fuzzy metaball |
| $\lambda_k$ | $\R$ | log-weight of the $k$-the fuzzy metaball |
| $d_{ijk}^{(t)}$    | $\R$ | intersection depth of ray corresponding to pixel $(i, j)$ at frame $t$ with the $k$-th fuzzy metaball |
| $q_{ijk}^{(t)}$    | $\R$ | the value of the quadratic form of $k$-th fuzzy metaball at the intersection of ray $(i, j)$ at frame $t$ |
| $\tilde{l}_{ijk}^{(t)}$    | $\R$ | likelihood exponent of the $k$-th fuzzy metaball for pixel $(i, j)$ at frame $t$ |
| $\tilde{w}_{ijk}^{(t)}$    | $\R$ | unnormalized depth blending weight of the $k$-th fuzzy metaball for pixel $(i, j)$ at frame $t$ |
| $\bar{d}_{ij}^{(t)}$    | $\R$ | depth value of pixel $(i, j)$ at frame $t$ |
| $c_{ij}^{(t)}$    | $[0, 1]$ | confidence value of pixel $(i, j)$ at frame $t$ |
| $\L_c$    | $\R$ | contour loss  (a function of $c_{ij}^{(t)}$) |
| $\L_d$    | $\R$ | depth loss  (a function of $d_{ij}^{(t)}$) |


## Forward Pass

\begin{align*}
(\tau^{(t)}, \rho^{(t)}) &:= \pi^{(t)} \\
v_{ij}^{(t)} &:= \rho^{(t)}v_{ij} \\
d_{ijk}^{(t)} &:= \frac{(\mu_k - \tau^{(t)})^\top\Pi_kv_{ij}^{(t)}}
    {{v_{ij}^{(t)}}^\top\Pi_kv_{ij}^{(t)}} \\
q_{ijk}^{(t)} &:= (\mu_k - \tau^{(t)} - d_{ijk}^{(t)}v_{ij}^{(t)})^\top
    \Pi_k (\mu_k - \tau^{(t)} - d_{ijk}^{(t)}v_{ij}^{(t)}) \\
\tilde{l}_{ijk}^{(t)} &:= -\frac{1}{2} q_{ijk}^{(t)} + \lambda_k \\
\tilde{w}_{ijk}^{(t)} &:=
    \exp\left(\beta_1 \tilde{l}_{ijk}^{(t)} - \beta_2 d_{ijk}^{(t)}\right) \\
\bar{d}_{ij}^{(t)} &:=
    \frac{\sum_{k=1}^N \tilde{w}_{ijk}^{(t)} d_{ijk}^{(t)}}
         {\sum_{k=1}^N \tilde{w}_{ijk}^{(t)}} \\
c_{ij}^{(t)} &:= 1 - \exp\left(-\sum_{k=1} \exp\left(\tilde{l}_{ijk}^{(t)}\right)\right)
\end{align*}

![Dependency graph of the variables in the forward pass using plate
notation](plate_diagram.png){width=540}

## Depth Backward Pass

\begin{align*}
\frac{\partial \L_d}{\partial \tilde{w}_{ijk}^{(t)}} &= 
    \frac{\partial \L_d}{\partial \bar{d}_{ij}^{(t)}}
    \frac{\partial \bar{d}_{ij}^{(t)}}{\partial \tilde{w}_{ijk}^{(t)}}\\
\frac{\partial \L_d}{\partial q_{ijk}^{(t)}} &= 
    \frac{\partial \L_d}{\partial \tilde{w}_{ijk}^{(t)}}
    \frac{\partial \tilde{w}_{ijk}^{(t)}}{\partial q_{ijk}^{(t)}}\\
\frac{\partial \L_d}{\partial d_{ijk}^{(t)}} &= 
    \frac{\partial \L_d}{\partial q_{ijk}^{(t)}}
    \frac{\partial q_{ijk}^{(t)}}{\partial d_{ijk}^{(t)}}
    + \frac{\partial \L_d}{\partial \tilde{w}_{ijk}^{(t)}}
    \frac{\partial \tilde{w}_{ijk}^{(t)}}{\partial d_{ijk}^{(t)}}
    + \frac{\partial \L_d}{\partial \bar{d}_{ij}^{(t)}}
    \frac{\partial \bar{d}_{ij}^{(t)}}{\partial d_{ijk}^{(t)}} \\
\frac{\partial \L_d}{\partial \tau^{(t)}} &=
    \sum_{i,j}\sum_k \frac{\partial \L_d}{\partial q_{ijk}^{(t)}}
    \frac{\partial q_{ijk}^{(t)}}{\partial \tau^{(t)}}
    + \sum_{i,j}\sum_k \frac{\partial \L_d}{\partial d_{ijk}^{(t)}}
    \frac{\partial d_{ijk}^{(t)}}{\partial \tau^{(t)}} \\
\frac{\partial \L_d}{\partial v_{ij}^{(t)}} &=
    \sum_k \frac{\partial \L_d}{\partial q_{ijk}^{(t)}}
    \frac{\partial q_{ijk}^{(t)}}{\partial v_{ij}^{(t)}}
    + \sum_k \frac{\partial \L_d}{\partial d_{ijk}^{(t)}}
    \frac{\partial d_{ijk}^{(t)}}{\partial v_{ij}^{(t)}} \\
\frac{\partial \L_d}{\partial \rho^{(t)}} &=
    \sum_{i,j} \frac{\partial \L_d}{\partial v_{ij}^{(t)}}
           \frac{\partial v_{ij}^{(t)}}{\partial \rho^{(t)}} \\
\frac{\partial \L_d}{\partial \lambda_k} &= 
    \sum_t \sum_{i, j}
    \frac{\partial \L_d}{\partial \tilde{w}_{ijk}^{(t)}}
    \frac{\partial \tilde{w}_{ijk}^{(t)}}{\partial \lambda_k} \\
\frac{\partial \L_d}{\partial \mu_k} &= 
    \sum_t \sum_{i, j} \frac{\partial \L_d}{\partial q_{ijk}^{(t)}}
        \frac{\partial q_{ijk}^{(t)}}{\partial \mu_k}
    + \sum_t \sum_{i, j} \frac{\partial \L_d}{\partial d_{ijk}^{(t)}}
        \frac{\partial d_{ijk}^{(t)}}{\partial \mu_k} \\
\frac{\partial \L_d}{\partial \Pi_k} &= 
    \sum_t \sum_{i, j} \frac{\partial \L_d}{\partial q_{ijk}^{(t)}}
        \frac{\partial q_{ijk}^{(t)}}{\partial \Pi_k}
    + \sum_t \sum_{i, j} \frac{\partial \L_d}{\partial d_{ijk}^{(t)}}
        \frac{\partial d_{ijk}^{(t)}}{\partial \Pi_k} \\
\end{align*}


## Confidence Backward Pass

\begin{align*}
\frac{\partial \L_c}{\partial d_{ijk}^{(t)}} &= 
    \frac{\partial \L_c}{\partial q_{ijk}^{(t)}}
    \frac{\partial q_{ijk}^{(t)}}{\partial d_{ijk}^{(t)}}\\
\frac{\partial \L_c}{\partial q_{ijk}^{(t)}} &= 
    \frac{\partial \L_c}{\partial c_{ij}^{(t)}}
    \frac{\partial c_{ij}^{(t)}}{\partial q_{ijk}^{(t)}}\\
\frac{\partial \L_c}{\partial \tau^{(t)}} &= 
    \sum_{i,j}\sum_k \frac{\partial \L_c}{\partial d_{ijk}^{(t)}}
        \frac{\partial d_{ijk}^{(t)}}{\partial \tau^{(t)}}
    + \sum_{i,j}\sum_k \frac{\partial \L_c}{\partial q_{ijk}^{(t)}}
        \frac{\partial q_{ijk}^{(t)}}{\partial \tau^{(t)}}\\
\frac{\partial \L_c}{\partial v_{ij}^{(t)}} &= 
    \sum_{k} \frac{\partial \L_c}{\partial d_{ijk}^{(t)}}
        \frac{\partial d_{ijk}^{(t)}}{\partial v_{ij}^{(t)}}
    + \sum_{k} \frac{\partial \L_c}{\partial q_{ijk}^{(t)}}
        \frac{\partial q_{ijk}^{(t)}}{\partial v_{ij}^{(t)}} \\
\frac{\partial \L_c}{\partial \rho^{(t)}} &= 
    \sum_{i,j} \frac{\partial \L_c}{\partial v_{ij}^{(t)}}
        \frac{\partial v_{ij}^{(t)}}{\partial \rho^{(t)}} \\
\frac{\partial \L_c}{\partial \lambda_k} &= 
    \sum_{t}\sum_{i,j} \frac{\partial \L_c}{\partial c_{ij}^{(t)}}
        \frac{\partial c_{ij}^{(t)}}{\partial \lambda_k} \\
\frac{\partial \L_c}{\partial \mu_k} &= 
    \sum_{t}\sum_{i,j} \frac{\partial \L_c}{\partial q_{ijk}^{(t)}}
        \frac{\partial q_{ijk}^{(t)}}{\partial \mu_k}
    + \sum_{t}\sum_{i,j} \frac{\partial \L_c}{\partial d_{ijk}^{(t)}}
        \frac{\partial d_{ijk}^{(t)}}{\partial \mu_k} \\
\frac{\partial \L_c}{\partial \Pi_k} &= 
    \sum_{t}\sum_{i,j} \frac{\partial \L_c}{\partial q_{ijk}^{(t)}}
        \frac{\partial q_{ijk}^{(t)}}{\partial \Pi_k}
    + \sum_{t}\sum_{i,j} \frac{\partial \L_c}{\partial d_{ijk}^{(t)}}
        \frac{\partial d_{ijk}^{(t)}}{\partial \Pi_k}
\end{align*}

We can simplify the backward pass by inlining those derivatives that depend on
fixed $i$, $j$, and $t$. We get:

\begin{align*}
\frac{\partial \L_c}{\partial \tau^{(t)}} &= 
    \sum_{i,j}\sum_k \frac{\partial \L_c}{\partial c_{ij}^{(t)}}
        \frac{\partial c_{ij}^{(t)}}{\partial q_{ijk}^{(t)}} \left(
            \frac{\partial q_{ijk}^{(t)}}{\partial d_{ijk}^{(t)}}
            \frac{\partial d_{ijk}^{(t)}}{\partial \tau^{(t)}}
            + \frac{\partial q_{ijk}^{(t)}}{\partial \tau^{(t)}}
      \right)\\
\frac{\partial \L_c}{\partial \rho^{(t)}} &= 
    \sum_{i,j} \sum_{k} \frac{\partial \L_c}{\partial c_{ij}^{(t)}}
    \frac{\partial c_{ij}^{(t)}}{\partial q_{ijk}^{(t)}} \left(
        \frac{\partial q_{ijk}^{(t)}}{\partial d_{ijk}^{(t)}}
        \frac{\partial d_{ijk}^{(t)}}{\partial v_{ij}^{(t)}}
        + \frac{\partial q_{ijk}^{(t)}}{\partial v_{ij}^{(t)}}
    \right) 
        \frac{\partial v_{ij}^{(t)}}{\partial \rho^{(t)}} \\
\frac{\partial \L_c}{\partial \lambda_k} &= 
    \sum_{t}\sum_{i,j} \frac{\partial \L_c}{\partial c_{ij}^{(t)}}
        \frac{\partial c_{ij}^{(t)}}{\partial \lambda_k} \\
\frac{\partial \L_c}{\partial \mu_k} &= 
    \sum_{t}\sum_{i,j} \frac{\partial \L_c}{\partial c_{ij}^{(t)}}
        \frac{\partial c_{ij}^{(t)}}{\partial q_{ijk}^{(t)}} \left(
        \frac{\partial q_{ijk}^{(t)}}{\partial \mu_k}
        + \frac{\partial q_{ijk}^{(t)}}{\partial d_{ijk}^{(t)}}
          \frac{\partial d_{ijk}^{(t)}}{\partial \mu_k}
    \right) \\
\frac{\partial \L_c}{\partial \Pi_k} &= 
    \sum_{t}\sum_{i,j} \frac{\partial \L_c}{\partial c_{ij}^{(t)}}
        \frac{\partial c_{ij}^{(t)}}{\partial q_{ijk}^{(t)}} \left(
        \frac{\partial q_{ijk}^{(t)}}{\partial \Pi_k}
        + \frac{\partial q_{ijk}^{(t)}}{\partial d_{ijk}^{(t)}}
          \frac{\partial d_{ijk}^{(t)}}{\partial \Pi_k}
    \right) \\
\end{align*}

## Sympy derivation of confidence backward pass

```{python}
import sympy as sp
from sympy import symbols, IndexedBase, Idx
from sympy.printing.latex import latex
```

```{python}
def simplify_subterm(expr, subterm_idx):
    args = list(expr.args)
    args[subterm_idx] = sp.simplify(args[subterm_idx])
    return expr.func(*args)

```

```{python}
N, T, H, W = symbols('N T H W', integer=True)

i, j, k, t = map(Idx, 'i j k t'.split())
i_, j_, k_, t_ = map(Idx, "i' j' k' t'".split())

i_assumption = sp.Q.nonnegative(i) & sp.Q.le(i, H - 1)
j_assumption = sp.Q.nonnegative(j) & sp.Q.le(j, W - 1)
k_assumption = sp.Q.nonnegative(k) & sp.Q.le(k, N - 1)
t_assumption = sp.Q.nonnegative(t) & sp.Q.le(t, T - 1)

v, tau, mu = [sp.MatrixSymbol(name, 3, 1) for name in r'v \tau \mu'.split()]
Pi  = sp.MatrixSymbol(r'\Pi', 3, 3)

Pi_assumption = sp.Q.symmetric(Pi)

lmbda, d, q, l, w, c, L_c, y = map(
    sp.Symbol, r'\lambda d q l w c L_c y'.split()
)

lmbda, q = map(IndexedBase, r'\lambda q'.split())
```

```{python}
cross_entropy = lambda p, y: -(1 - y) * sp.log(1 - p) - y * sp.log(p)


c_expr = 1 - sp.exp(-sp.Sum(sp.exp(-q[i, j, k_, t]/2 + lmbda[k_]), (k_, 0, N-1)))
L_c_expr = cross_entropy(c, y)

q_expr = (mu - tau - d*v).T * Pi * (mu - tau - d*v)
d_expr = (mu - tau).T * Pi * v / (v.T * Pi * v)
```

---

$\partial \L_c / \partial c_{ij}^{(t)} =$
```{python}
sp.diff(L_c_expr, c)
```

---

$\partial c_{ij}^{(t)} / \partial \lambda_{k} =$
```{python}
sp.refine(sp.diff(c_expr, lmbda[k]).doit(), k_assumption)
```

---

$\partial c_{ij}^{(t)} / \partial q_{ijk}^{(t)} =$
```{python}
sp.refine(sp.diff(c_expr, q[i, j, k, t]).doit(), k_assumption)
```

---

$\partial q_{ijk}^{(t)} / \partial \Pi_k=$
```{python}
sp.diff(q_expr, Pi)
```

---

$\partial q_{ijk}^{(t)} / \partial \mu_k=
-\partial q_{ijk}^{(t)} / \partial \tau^{(t)}=
-\frac{1}{d}\partial q_{ijk}^{(t)} / \partial v_{ij}^{(t)}=$
```{python}
sp.diff(q_expr, mu)
```
$$
= 2\Pi(\mu - dv - \tau)
$$

---

$\partial q_{ijk}^{(t)} / \partial d_{ijk}^{(t)}=$
```{python}
sp.diff(q_expr, d)
```
$$
= -2(\mu - \tau - dv)^T\Pi v
$$


---

$\partial d_{ijk}^{(t)} / \partial \Pi_k=$
```{python}
sp.diff(d_expr, Pi)
```
$$
= \frac{1}{v^T \Pi v} (\mu - \tau) v^T
-\frac{v^T \Pi (\mu - \tau)}{(v^T \Pi v)^2} v v^{T}
$$

---

$\partial d_{ijk}^{(t)} / \partial v_{ij}^{(t)}=$
```{python}
sp.diff(d_expr, v)
```
$$
= -2\frac{v^T \Pi (\mu - \tau)}{(v^T \Pi v)^2} \Pi v 
+ \frac{1}{v^T \Pi v} \Pi (\mu - \tau) 
$$

---

$\partial d_{ijk}^{(t)} / \partial \tau^{(t)}=
-\partial d_{ijk}^{(t)} / \partial \mu_k=$
```{python}
sp.diff(d_expr, tau)
```

